import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import ExcelJS from 'exceljs';
import {createApplication} from '../../server/app.mjs';
import {setAdminPassword,digest} from '../../server/store.mjs';
const source=()=>({title:'测试考试批次',titleEn:'Exam series',start:'2026-09-21',end:'2026-10-04',rooms:[{name:'2101',rows:5,columns:5}],sessions:[{id:'math',title:'数学 Paper 1',titleEn:'Math Paper 1',division:'high',grades:['G10'],date:'2026-09-23',start:'08:15',end:'09:45',rooms:['2101']},{id:'english',title:'英语',division:'middle',grades:['G8'],date:'2026-09-23',start:'08:30',end:'10:00',rooms:['2101']}],seats:[{examId:'math',room:'2101',row:1,column:1,className:'G10A',name:'示例甲',englishName:'Sample A'},{examId:'english',room:'2101',row:1,column:2,className:'G8A',name:'示例乙',englishName:'Sample B'}]});
test('exam publication, private seating, per-account choices, import validation and PDFs',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'calendar-exams-')),instance=createApplication({dataDir:directory,origin:'http://calendar.test'}),server=instance.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
 const base=`http://127.0.0.1:${server.address().port}`,headers={Origin:'http://calendar.test','Content-Type':'application/json'};
 const call=(path,method='GET',body,cookie='')=>fetch(base+'/api'+path,{method,headers:{...headers,...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});
 try{
  assert.equal((await call('/admin/exams','POST',source())).status,401);
  await setAdminPassword(instance.db,'admin','exam-testing-password');const login=await call('/login','POST',{username:'admin',password:'exam-testing-password'}),admin=login.headers.get('set-cookie').split(';')[0];
  let res=await call('/admin/exams','POST',source(),admin);assert.equal(res.status,201);let batch=await res.json(),path='/admin/exams/'+batch.id;
  assert.equal(batch.timeSlots.length,5);assert.deepEqual(batch.timeSlots[0],{start:'08:10',end:'09:40'});
  assert.equal((await call(path,'PUT',{...batch,timeSlots:[{start:'09:00',end:'08:00'}]},admin)).status,422);
  assert.equal((await call(path,'PUT',{...batch,timeSlots:[{start:'08:00',end:'10:00'},{start:'09:00',end:'11:00'}]},admin)).status,422);
  res=await call(path,'PUT',{...batch,timeSlots:[{start:'08:00',end:'10:00'},{start:'11:00',end:'12:30'}]},admin);assert.equal(res.status,200);batch=await res.json();
  assert.deepEqual(await (await call('/exams')).json(),[]);assert.equal((await call('/exams/'+batch.id)).status,404);
  res=await call(path+'/publish','POST',{version:batch.version},admin);assert.equal(res.status,200);batch=await res.json();
  const pub=await (await call('/exams/'+batch.id)).json();assert.equal(pub.sessions.length,2);assert.deepEqual(pub.timeSlots,[{start:'08:00',end:'10:00'},{start:'11:00',end:'12:30'}]);assert.equal(pub.seats,undefined);assert.equal(JSON.stringify(pub).includes('示例甲'),false);
  assert.equal((await call('/exams/'+batch.id+'/seats')).status,401);
  instance.db.prepare('INSERT INTO school_sessions VALUES(?,?,?,?)').run(digest('student-a'),'tenant:student-a','Student A',Date.now()+60000);
  instance.db.prepare('INSERT INTO school_sessions VALUES(?,?,?,?)').run(digest('student-b'),'tenant:student-b','Student B',Date.now()+60000);
  const a='school_session=student-a',b='school_session=student-b';
  assert.equal((await call('/exams/'+batch.id+'/choices','PUT',{ids:['math','english']},a)).status,200);
  assert.deepEqual(await (await call('/exams/'+batch.id+'/choices','GET',null,b)).json(),[]);
  assert.equal((await call('/exams/'+batch.id+'/choices','PUT',{ids:['not-published']},a)).status,422);
  res=await call(path+'/publish-seats','POST',{version:batch.version},admin);assert.equal(res.status,200);batch=await res.json();
  const seats=await (await call('/exams/'+batch.id+'/seats','GET',null,a)).json();assert.equal(seats.seats.length,2);
  const changed=structuredClone(batch);changed.sessions[0].start='08:00';res=await call(path,'PUT',changed,admin);assert.equal(res.status,200);batch=await res.json();
  assert.equal((await (await call('/exams/'+batch.id)).json()).sessions[0].start,'08:15');
  assert.equal((await call(path+'/publish-seats','POST',{version:batch.version},admin)).status,422);
  res=await call(path+'/publish','POST',{version:batch.version},admin);assert.equal(res.status,200);batch=await res.json();
  assert.equal((await (await call('/exams/'+batch.id)).json()).sessions[0].changed,true);
  assert.equal((await call('/exams/'+batch.id+'/seats','GET',null,a)).status,404);
  assert.deepEqual(await (await call('/exams/'+batch.id+'/choices','GET',null,a)).json(),['english','math']);
  const collision=structuredClone(batch);collision.seats[1].column=1;assert.equal((await call(path,'PUT',collision,admin)).status,422);
  const outOfBounds=structuredClone(batch);outOfBounds.rooms[0].rows=0;assert.equal((await call(path,'PUT',outOfBounds,admin)).status,422);
  const deleted=structuredClone(batch);deleted.sessions.shift();assert.equal((await call(path,'PUT',deleted,admin)).status,422);
  const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(Buffer.from(await (await call(path+'/template','GET',null,admin)).arrayBuffer()));
  const sheet=workbook.getWorksheet('座位数据');sheet.addRow(['math','2101',1,1,'G10','测试学生','Test']);
  let imported=await fetch(base+'/api'+path+'/import-preview',{method:'POST',headers:{Origin:'http://calendar.test',Cookie:admin,'Content-Type':'application/octet-stream'},body:await workbook.xlsx.writeBuffer()});assert.equal(imported.status,200);let preview=await imported.json();assert.equal(preview.errors.length,0);assert.equal(preview.seats.length,1);
  sheet.addRow(['english','2101',1,1,'G8','测试学生乙','Test B']);imported=await fetch(base+'/api'+path+'/import-preview',{method:'POST',headers:{Origin:'http://calendar.test',Cookie:admin,'Content-Type':'application/octet-stream'},body:await workbook.xlsx.writeBuffer()});preview=await imported.json();assert.match(preview.errors.join(''),/重复占用/);
  assert.equal((await call('/exams/'+batch.id+'/pdf?mine=1')).status,401);
  res=await call('/exams/'+batch.id+'/pdf?mine=1','GET',null,a);assert.equal(res.status,200);const pdf=Buffer.from(await res.arrayBuffer());assert.equal(pdf.subarray(0,4).toString(),'%PDF');assert.ok(pdf.length>4000);
  res=await call('/exams/'+batch.id+'/pdf?division=high');assert.equal(res.status,200);
  assert.equal((await call(path,'PUT',{...batch,version:1},admin)).status,409);
  batch.sessions[0].cancelled=true;res=await call(path,'PUT',batch,admin);batch=await res.json();res=await call(path+'/publish','POST',{version:batch.version},admin);assert.equal(res.status,200);
  assert.equal((await (await call('/exams/'+batch.id)).json()).sessions[0].cancelled,true);assert.deepEqual(await (await call('/exams/'+batch.id+'/choices','GET',null,a)).json(),['english','math']);
  const oauth=await fetch(base+'/api/school/login',{redirect:'manual'});assert.equal(oauth.headers.get('location'),'/?auth=unconfigured');
  assert.equal((await call('/school/logout','POST',null,a)).status,204);assert.equal((await call('/exams/'+batch.id+'/choices','GET',null,a)).status,401);
 }finally{await new Promise(r=>server.close(r));instance.close();await rm(directory,{recursive:true,force:true});}
});
