/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false cloudflare/worker-configuration.d.ts` (hash: 5a8a50071b0195a3463d87f13da7da8b)
interface __BaseEnv_Env {
	IMAGES: ImagesBinding;
	APP_ORIGIN: "https://calendar.keydion.com";
	SCHOOL_ID: "calendar";
	SCHOOL_NAME: "学校校历";
	SCHOOL_NAME_EN: "School calendar";
	SCHOOL_TIMEZONE: "Asia/Shanghai";
	ADMIN_BOOTSTRAP: string;
	SCHOOLS: DurableObjectNamespace<import("../dist/backend/worker").SchoolCalendar>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../dist/backend/worker");
		durableNamespaces: "SchoolCalendar";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "SCHOOL_ID" | "SCHOOL_NAME" | "SCHOOL_NAME_EN" | "SCHOOL_TIMEZONE" | "ADMIN_BOOTSTRAP">> {}
}
