/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false cloudflare/worker-configuration.d.ts` (hash: cea0aca827a8e4b2710adc1eb0bf11b7)
interface __BaseEnv_Env {
	IMAGES: ImagesBinding;
	MICROSOFT_LOGIN_URL: "https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize";
	APP_ORIGIN: "https://calendar.keydion.com";
	SCHOOL_ID: "calendar";
	SCHOOL_TIMEZONE: "Asia/Shanghai";
	ADMIN_BOOTSTRAP: string;
	SCHOOLS: DurableObjectNamespace<import("../dist/backend/worker").SchoolCalendar>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../dist/backend/worker");
		durableNamespaces: "SchoolCalendar";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MICROSOFT_LOGIN_URL" | "APP_ORIGIN" | "SCHOOL_ID" | "SCHOOL_TIMEZONE" | "ADMIN_BOOTSTRAP">> {}
}
