/** @type {SchoolEvent[]} */
const SAMPLE_EVENTS = [
  {id:'opening',title:['新学期开学典礼','Autumn opening assembly'],type:'activity',start:'2026-09-01',time:'08:30',endTime:'09:30',scope:['schoolwide'],location:['学校礼堂','School auditorium'],host:['学生发展中心','Student development office'],description:['新学期开学典礼，请各学部同学按学校安排入场。','Welcome assembly for the new term. Please follow your division’s arrival arrangements.']},
  {id:'reading',title:['图书馆阅读分享会','Library reading circle'],type:'activity',start:'2026-09-04',time:'15:30',endTime:'16:30',scope:['primary'],location:['图书馆一楼','Library, ground floor'],host:['图书馆','School library']},
  {id:'science',title:['科学探索开放日','Science discovery day'],type:'activity',start:'2026-09-08',time:'14:00',endTime:'16:00',scope:['primary','middle'],location:['科学实验中心','Science lab centre'],host:['科学教研组','Science department']},
  {id:'debate',title:['英语辩论赛初赛','English debate heats'],type:'competition',start:'2026-09-10',time:'15:00',endTime:'17:00',scope:['middle','high'],location:['报告厅','Lecture hall'],host:['英语教研组','English department']},
  {id:'midterm',title:['高中部阶段考试','High school assessment'],type:'exam',start:'2026-09-14',end:'2026-09-16',scope:['high'],location:['高中部教学楼','High school building'],host:['高中部教务处','High school academic office'],description:['考试期间请按照各学科公布的安排参加考试。具体考场与场次以教务处通知为准。','Follow the timetable issued by each subject team. Refer to the academic office notice for individual sessions and rooms.']},
  {id:'clubdue',title:['社团选报截止','Club selection closes'],type:'deadline',start:'2026-09-18',time:'17:00',scope:['middle','high'],host:['学生发展中心','Student development office'],description:['请在截止时间前通过学校选报表完成社团选择。','Submit your club choices through the school form before the deadline.'],registration:true},
  {id:'garden',title:['校园自然观察','Campus nature walk'],type:'activity',start:'2026-09-19',time:'09:00',endTime:'10:30',scope:['primary'],location:['校园植物园','School garden'],host:['小学部科学组','Primary science team']},
  {id:'readingweek',title:['校园阅读周','Campus reading week'],type:'activity',start:'2026-09-21',end:'2026-09-24',scope:['schoolwide'],location:['图书馆','School library'],host:['图书馆','School library'],description:['在阅读周里交换一本好书，分享一段喜欢的文字。各学部活动安排请关注图书馆公告。','Exchange a favourite book and share a passage during reading week. See the library notice for division activities.']},
  {id:'sports',title:['秋季运动会','Autumn sports day'],type:'competition',start:'2026-09-22',time:'08:30',endTime:'16:00',scope:['schoolwide'],location:['学校田径场','School athletics field'],host:['体育组','Physical education department'],oldDate:'2026-09-20',description:['田径项目与团队趣味赛。请穿着运动服，携带饮用水，按学部安排参加。','Track events and team games. Wear sports clothing, bring drinking water and follow your division’s arrangements.']},
  {id:'arts',title:['校园艺术节','Campus arts festival'],type:'activity',start:'2026-09-23',time:'14:00',endTime:'17:00',scope:['schoolwide'],location:['学校礼堂 · 一楼','School auditorium · Ground floor'],host:['艺术教研组 · 学生发展中心','Arts department · Student development office'],description:['用音乐、戏剧与创作，记录校园里的每一种热爱。欢迎三个学部的同学一起观看演出、参观学生作品展。','Celebrate school life through music, theatre and creative work. Students from all three divisions are welcome to enjoy the performances and student exhibition.'],extra:['演出 14:00 开始，建议提前 15 分钟入场。参与工作坊的同学请通过下方表单登记。','Performances begin at 14:00. Please arrive 15 minutes early. Use the form below to register for a workshop.'],registration:true},
  {id:'math',title:['数学思维挑战赛','Mathematical thinking challenge'],type:'competition',start:'2026-09-23',time:'10:00',endTime:'11:30',scope:['middle'],location:['初中部多功能室','Middle school activity room'],host:['数学教研组','Mathematics department']},
  {id:'makers',title:['创客工作坊','Maker workshop'],type:'activity',start:'2026-09-23',time:'13:00',endTime:'14:00',scope:['primary','middle'],location:['创客空间','Maker space'],host:['科学教研组','Science department'],registration:true},
  {id:'lecture',title:['生涯探索讲座','Pathways exploration talk'],type:'activity',start:'2026-09-23',time:'15:30',endTime:'16:30',scope:['high'],location:['报告厅','Lecture hall'],host:['学生发展中心','Student development office']},
  {id:'teamdue',title:['校队报名截止','School team registration closes'],type:'deadline',start:'2026-09-23',time:'17:00',scope:['middle','high'],host:['体育组','Physical education department'],registration:true},
  {id:'choir',title:['校园合唱音乐会','School choir concert'],type:'activity',start:'2026-09-24',time:'16:00',endTime:'17:00',scope:['schoolwide'],location:['学校礼堂','School auditorium'],host:['艺术教研组','Arts department'],cancelled:true,description:['本场音乐会因场地维护取消。后续安排将另行发布。','This concert has been cancelled due to venue maintenance. Any new arrangements will be announced separately.']},
  {id:'break',title:['秋季校假（示例）','Autumn school break (sample)'],type:'holiday',start:'2026-09-25',end:'2026-09-27',scope:['schoolwide'],host:['学校办公室','School office'],description:['用于展示跨日假期的虚构示例，不代表任何地区的法定节假日或真实学校放假安排。','Fictional data demonstrating a multi-day school break. These are not verified public holidays or an actual school schedule.']},
  {id:'primaryexam',title:['小学部学习回顾','Primary learning review'],type:'exam',start:'2026-09-28',scope:['primary'],location:['小学部各班教室','Primary classrooms'],host:['小学部教务处','Primary academic office']},
  {id:'middleexam',title:['初中部阶段考试','Middle school assessment'],type:'exam',start:'2026-09-29',end:'2026-09-30',scope:['middle'],location:['初中部教学楼','Middle school building'],host:['初中部教务处','Middle school academic office']},
  {id:'electives',title:['选课调整截止','Elective changes close'],type:'deadline',start:'2026-09-30',time:'17:00',scope:['high'],host:['高中部教务处','High school academic office'],description:['请在截止时间前确认本学期选修课调整结果。','Confirm your elective changes for the term before the deadline.'],registration:true}
];

// An independent review scene keeps the original 19-event regression set stable.
if(new URLSearchParams(location.search).get('scene')==='extended'){
  SAMPLE_EVENTS.push(
    ...Array.from({length:5},(_,i)=>({id:'extended-span-'+i,title:[`跨周示例 ${i+1}`,`Across-week sample ${i+1}`],type:'activity',start:'2026-09-23',end:'2026-09-29',scope:['schoolwide']})),
    {id:'media-demo',title:['校园艺术节海报与报名入口示例','Arts festival media sample'],type:'activity',start:'2026-09-23',time:'13:30',endTime:'17:00',scope:['schoolwide'],poster:'assets/event-poster.svg',registrationUrl:'https://example.org/?demo=school-calendar',qr:'sample'},
    {id:'qr-only',title:['仅二维码入口示例','QR-only sample'],type:'activity',start:'2026-09-24',scope:['middle'],qr:'sample'},
    {id:'link-only',title:['仅报名链接示例','Link-only sample'],type:'activity',start:'2026-09-24',scope:['high'],registrationUrl:'https://example.org/?demo=school-calendar'},
    {id:'missing-media',title:['图片不可用示例','Unavailable media sample'],type:'activity',start:'2026-09-24',scope:['schoolwide'],poster:'assets/missing-poster.png',qr:'broken'},
    {id:'english-only',title:['','An English-only event with a deliberately long title for checking text wrapping and missing optional information'],type:'holiday',start:'2026-09-26',scope:['schoolwide']}
  );
}
